### ISSUE TITLE
Networking Event Loop Delay

### ISSUE THREAD

**Issue by Obbay2** [huskyroboticsteam/Orpheus#61]
BaseStation Project > StartBaseStation.cs 
Update loop requires > 100 ms thread sleep otherwise UI locks up and must be force killed.

**Comment by blobjim** [comment]
It probably has to do with my ConsoleView class again. We may have to just use the Windows console if I can't find a way to improve it. I think it has something to do with synchronization. If you remove the ConsoleView the lag will probably go away.

**Comment by blobjim** [comment]
We could also look at using  https://github.com/dwmkerr/consolecontrol to embed a console in the application.

**Comment by blobjim** [comment]
I've almost got a working solution by replacing text.Dispatcher.BeginInvoke with text.Dispatcher.Invoke in ConsoleView, but it causes a deadlock that causes the program to continue running after application exit :(

**Comment by Obbay2** [comment]
I'm sure Cai and Jaden would be really happy if we never used Console.Write anywhere ever again anyways!

**Comment by Obbay2** [comment]
I also agree printing "Gamepad Not Connected" is a bit silly, but we have no other mechanism right now to indicate when the controllers are connected or not. It really needs to be broken down by individual controller, since right now it just indicates a single controller. Controllers are a big point of improvement for next year, but right now sketchy will probably do.

**Comment by blobjim** [comment]
I haven't successfully found a way to increase the performance of the ConsoleView so the application doesn't stall. I believe there's just too much console output from the packet logging.

**Comment by Obbay2** [comment]
Could we just spawn a command prompt process and redirect standard out there for now? I don't think that will screw up any other systems, but I'm not 100% sure. We can resolve this bug after competition, since it is a good idea and when we move over to actual logging we can add filters and other useful things.

**Comment by Obbay2** [comment]
Will close once pull request is merged.
