### ISSUE TITLE
GStreamerServer Reimplementation

### ISSUE THREAD

**Issue by Obbay2** [huskyroboticsteam/Orpheus#81]
C# not C++ if possible, due to easier access to a C# binding of some gstreamer features.

**Comment by blobjim** [comment]
Gstreamer-sharp? https://gstreamer.freedesktop.org/modules/gstreamer-sharp.html

**Comment by blobjim** [comment]
ayyyy lmao figured out the gstreamer dependencies. you can use http://www.dependencywalker.com/ (officially endorsed by Microsoft!) to find the dependencies for libgstreamer-1.0-0.dll after you've got all gstream dlls in a single folder. Then it will tell you it needs libgstwebrtc, so do the same thing for that and bingo it works.

**Comment by blobjim** [comment]
I removed the xcopy commands but added some stuff to the .csproj file that will do the same thing. I still need to update it to also do that for gstreamer libraries. Where should we look for the gstreamer dlls to be copied? What directory should libraries be in in general?

**Comment by blobjim** [comment]
EntryPoint.csproj in the BaseStationRefactor branch

**Comment by blobjim** [comment]
I think we should all get acquainted with MSBuild so anyone can add some build steps. I think xml for building is really stupid, but it's probably better than using something not supported by Visual Studio that we have to convert everything to.

**Comment by blobjim** [comment]
I still don't understand MSBuild very well. It's weird how each project has its own bin/Debug but only one of them is really 'used' when you run a program.

**Comment by Obbay2** [comment]
Yep it's pretty silly.

**Comment by Obbay2** [comment]
If we are concerned about performance we probably don't want to do the weird compilation thing with building the Arm solution inside the basestation project either.

**Comment by Obbay2** [comment]
What is the desired way for getting the GStreamer dlls for running into the bin directory? Just copy them manually once? I can't run the project currently due to the missing DLLs.

**Comment by blobjim** [comment]
For now just copy the required dlls.

**Comment by blobjim** [comment]
What is the Arm pre-build command doing again?

**Comment by Obbay2** [comment]
It get's the MSBuild executable on the system, and the builds the Arm/ArmBaseStation/Arm.sln because the dlls output by that build are references in the main basestation project somewhere.

**Comment by blobjim** [comment]
I just realized that you can actually include a project in multiple solutions.

**Comment by Obbay2** [comment]
Lol let me know how that works I've never been able to figure that one out, if you know it, amazing!!

**Comment by blobjim** [comment]
It works. I can't believe we never thought of this before.

**Comment by blobjim** [comment]
It's been pushed to pull request #87 .

**Comment by Obbay2** [comment]
I will consider for the UI portion of this task using Media Foundation to avoid the gstreamer dlls altogether if possible.

**Comment by blobjim** [comment]
Are you ready to merge the pull request with master? Any files added to a folder 'libraries' in the BaseStation folder will be added to the EntryPoint output directory. Not sure if that will be final at all.
